In [2]:
import numpy as np 

In [16]:
def euclidean_distance(x, y):
    minus = x-y
    print(f"minus {minus.shape}: {minus}")
    pwr_of = np.pow(minus, 2)
    print(f"pwr_of {pwr_of.shape}: {pwr_of}")
    summed = np.sum(pwr_of, axis=1)
    print(f"summed {summed.shape}: {summed}")
    return summed

In [15]:
anchor = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

positive = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])

negative = np.array([
    [100, 200, 300, 400],
    [500, 600, 700, 800]
])

print(euclidean_distance(positive, negative))

minus (2, 4): [[ -90 -180 -270 -360]
 [-450 -540 -630 -720]]
pwr_of (2, 4): [[  8100  32400  72900 129600]
 [202500 291600 396900 518400]]
summed (4,): [210600 324000 469800 648000]
[210600 324000 469800 648000]
